<?php
$containername = gethostname();
if (getenv("CONTAINERNAME") !== false ) {
$containername = getenv("CONTAINERNAME");
}
?>
<html>
<head>
<title>Maintenance message from <?php echo $containername;?></title>
</head>
<body>
<?php
echo "<b>The web app is undergoing maintenance. Please try again later.</b><br>";
echo "This message was generated by $containername.";
?>
</body>
</html>
